# Generated by Django 5.2.15 on 2026-06-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_galleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='image',
            field=models.ImageField(blank=True, help_text='Use this for image content', null=True, upload_to='site_images/'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='value',
            field=models.TextField(blank=True, help_text='The text or HTML content', null=True),
        ),
    ]
