# Generated by Django 5.2.15 on 2026-06-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitecontent_image_alter_sitecontent_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='video',
            field=models.FileField(blank=True, help_text='Use this for video content (mp4/webm)', null=True, upload_to='site_videos/'),
        ),
    ]
