# Generated by Django 5.2.15 on 2026-06-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sitecontent_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='drivetrain',
            field=models.CharField(blank=True, help_text='e.g. AWD, RWD, FWD, 4x4', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='engine_type',
            field=models.CharField(blank=True, help_text='e.g. V6, Electric, Hybrid', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='exterior_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='full_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Required for financing', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='interior_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(blank=True, help_text='Vehicle Identification Number', max_length=17, null=True, unique=True),
        ),
    ]
