# Generated by Django 5.2.15 on 2026-06-18 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_financingapplication_user_jobapplication_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeInRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('vin', models.CharField(blank=True, max_length=50, null=True, verbose_name='VIN')),
                ('condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=20)),
                ('interested_in', models.CharField(blank=True, help_text='What vehicle are you looking to upgrade to?', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('photos', models.FileField(blank=True, help_text='Upload a ZIP file or image of your vehicle', null=True, upload_to='trade_ins/photos/')),
                ('status', models.CharField(choices=[('pending', 'Pending Valuation'), ('offer_made', 'Offer Made'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('offer_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade_in_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
