# Generated by Django 5.2.15 on 2026-06-18 23:50

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rentalrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(default=core.models.generate_tracking_id, editable=False, max_length=20, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('delivery_address', models.TextField()),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('carrier_assigned', 'Carrier Assigned'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered')], default='processing', max_length=30)),
                ('estimated_delivery_date', models.DateField(blank=True, null=True)),
                ('current_location', models.CharField(blank=True, help_text='e.g. Dallas, TX', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, help_text='Public notes for the customer tracking this shipment.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='core.vehicle')),
            ],
        ),
    ]
