# Generated by Django 5.2.15 on 2026-06-19 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_shipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='origin_address',
            field=models.CharField(default='Houston, TX', max_length=255),
        ),
    ]
