# Generated by Django 5.2.15 on 2026-06-19 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_shipment_origin_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='tracking_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
