# Generated by Django 5.2.15 on 2026-06-19 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_shipment_tracking_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalrequest',
            name='delivery_address',
            field=models.TextField(blank=True, help_text='Where the vehicle will be delivered', null=True),
        ),
        migrations.AddField(
            model_name='tradeinrequest',
            name='pickup_address',
            field=models.TextField(blank=True, help_text='Where the vehicle will be picked up', null=True),
        ),
        migrations.AlterField(
            model_name='tradeinrequest',
            name='condition',
            field=models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', max_length=20),
        ),
        migrations.AlterField(
            model_name='tradeinrequest',
            name='interested_in',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tradeinrequest',
            name='photos',
            field=models.FileField(blank=True, null=True, upload_to='trade_in_photos/'),
        ),
        migrations.AlterField(
            model_name='tradeinrequest',
            name='vin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
