# Generated by Django 5.2.15 on 2026-06-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_geminiapikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'AI Bulk Importer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HiggsfieldAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_id', models.CharField(help_text='Higgsfield API Key ID', max_length=255)),
                ('key_secret', models.CharField(help_text='Higgsfield API Key Secret', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Higgsfield API Key',
                'verbose_name_plural': 'Higgsfield API Keys',
            },
        ),
        migrations.AlterModelOptions(
            name='geminiapikey',
            options={'verbose_name': 'Gemini API Key', 'verbose_name_plural': 'Gemini API Keys'},
        ),
        migrations.RenameField(
            model_name='geminiapikey',
            old_name='added_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='geminiapikey',
            name='key',
            field=models.CharField(help_text='Gemini API Key', max_length=255, unique=True),
        ),
    ]
