# Generated by Django 5.2.15 on 2026-06-19 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_bulkimport_higgsfieldapikey_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HiggsfieldAPIKey',
        ),
    ]
