# Generated by Django 5.2.15 on 2026-06-22 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_delete_higgsfieldapikey'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='tracking_provider',
            field=models.CharField(blank=True, help_text='e.g. UPS, FedEx, Shippo, AfterShip', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='InstallmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('tier1', 'Tier 1 (Drive Now - >= 60% Down)'), ('tier2', 'Tier 2 (Layaway - < 60% Down)')], default='tier2', max_length=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('down_payment_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('principal_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('accumulated_penalty_interest', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('monthly_due_date', models.IntegerField(blank=True, help_text='Day of the month payment is due', null=True)),
                ('is_vehicle_released', models.BooleanField(default=False)),
                ('is_fully_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='installment_plan', to='core.financingapplication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_plans', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_plans', to='core.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_type', models.CharField(choices=[('down_payment', 'Down Payment'), ('installment', 'Installment Payment'), ('penalty', 'Penalty Payment'), ('rental', 'Rental Payment')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_method', models.CharField(blank=True, help_text='e.g. Stripe, Crypto Wallet, Bank Transfer', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('installment_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.installmentplan')),
                ('rental_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.rentalrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
