# Generated by Django 5.2.15 on 2026-06-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_shipment_tracking_provider_installmentplan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='minimum_down_payment_percent',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Minimum down payment percentage (e.g. 10.00 for 10%)', max_digits=5),
        ),
    ]
