# Generated by Django 5.2.15 on 2026-06-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_vehicle_minimum_down_payment_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentplan',
            name='delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'Pending Scheduling'), ('scheduled', 'Scheduled for Delivery'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered & Handed Over')], default='pending', max_length=50),
        ),
    ]
