# Generated by Django 5.2.15 on 2026-06-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_installmentplan_delivery_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentplan',
            name='delivery_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
