# Generated by Django 5.2.15 on 2026-06-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_installmentplan_delivery_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='origin_address',
            field=models.CharField(default='2333 Ponce de Leon Blvd., Suite 700, Coral Gables, FL 33134, USA', max_length=255),
        ),
    ]
