# Generated by Django 5.2.15 on 2026-06-24 11:40

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_shipment_origin_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financingapplication',
            name='drivers_license_file',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='financing/licenses/'),
        ),
        migrations.AlterField(
            model_name='financingapplication',
            name='government_id_file',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='financing/ids/'),
        ),
        migrations.AlterField(
            model_name='financingapplication',
            name='proof_of_income_file',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='financing/income/'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='resumes/'),
        ),
    ]
