# Generated by Django 5.2.15 on 2026-06-25 01:22

import ryder_pro.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_financingapplication_drivers_license_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontent',
            name='video',
            field=models.FileField(blank=True, help_text='Use this for video content (mp4/webm)', null=True, storage=ryder_pro.storage.CustomVideoMediaCloudinaryStorage(), upload_to='site_videos/'),
        ),
    ]
