# Generated by Django 5.2.15 on 2026-06-27 21:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_sitecontent_video'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Mack Anthem Long-Haul #1'", max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('asset_type', models.CharField(choices=[('truck', 'Truck'), ('van', 'Van'), ('bike', 'Bike')], default='truck', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='invest/assets/')),
                ('description', models.TextField(blank=True, null=True)),
                ('total_value', models.DecimalField(decimal_places=2, help_text='Total value of the vehicle, e.g. 120000.00', max_digits=12)),
                ('amount_funded', models.DecimalField(decimal_places=2, default=0, help_text='Total amount invested by users so far', max_digits=12)),
                ('min_investment', models.DecimalField(decimal_places=2, default=100, help_text='Minimum amount a user can invest', max_digits=12)),
                ('daily_return_percent', models.DecimalField(decimal_places=3, default=0.5, help_text='Daily earnings as a percent of the invested amount, e.g. 0.5 for 0.5%/day', max_digits=6)),
                ('is_active', models.BooleanField(default=True, help_text='Show on the invest marketplace and accept new investments')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="e.g. 'June 2026 Window'", max_length=100)),
                ('opens_at', models.DateTimeField(help_text='When the window opens')),
                ('closes_at', models.DateTimeField(help_text='When the window closes (e.g. 2 days later)')),
                ('fee_percent', models.DecimalField(decimal_places=2, default=5, help_text='Fee charged on withdrawals, as a percent of the amount', max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-opens_at'],
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Principal invested', max_digits=12)),
                ('contract_months', models.PositiveIntegerField(default=1, help_text='Contract length chosen by the investor, in months')),
                ('daily_return_percent', models.DecimalField(decimal_places=3, help_text="Snapshot of the asset's daily rate at time of investing", max_digits=6)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('last_accrued_on', models.DateField(default=django.utils.timezone.localdate)),
                ('accrued_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('matured', 'Matured'), ('withdrawn', 'Withdrawn'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investments', to='core.investmentasset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_type', models.CharField(choices=[('deposit', 'Deposit'), ('investment', 'Investment'), ('earning', 'Earning'), ('withdrawal', 'Withdrawal'), ('fee', 'Withdrawal Fee')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.investment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestorWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text='Funds available to invest or withdraw', max_digits=12)),
                ('total_deposited', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_withdrawn', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_earned', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investor_wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Gross amount requested', max_digits=12)),
                ('fee', models.DecimalField(decimal_places=2, default=0, help_text='Fee deducted from the payout', max_digits=12)),
                ('payout_method', models.CharField(blank=True, help_text='Bank / crypto / PayPal details', max_length=100, null=True)),
                ('payout_details', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to=settings.AUTH_USER_MODEL)),
                ('window', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='core.withdrawalwindow')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
