# Generated by Django 5.2.15 on 2026-06-27 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_investmentasset_withdrawalwindow_investment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorwallet',
            name='accumulated_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cumulative withdrawal fee the investor must pay to release withdrawals. Carries over and stacks each unpaid window.', max_digits=12),
        ),
        migrations.AddField(
            model_name='investorwallet',
            name='total_fees_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='fee_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='investmentasset',
            name='min_investment',
            field=models.DecimalField(decimal_places=2, default=2000, help_text='Minimum amount a user can invest (starts at $2,000)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount the investor will receive once the fee is paid', max_digits=12),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fee the investor must PAY to release this withdrawal', max_digits=12),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('pending_fee', 'Awaiting Fee Payment'), ('approved', 'Fee Paid — Awaiting Payout'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='pending_fee', max_length=20),
        ),
    ]
