# Generated by Django 5.2.15 on 2026-06-27 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_investorwallet_accumulated_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalwindow',
            name='fee_flat_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Used when fee type is 'Flat amount' — e.g. 2500.00", max_digits=12),
        ),
        migrations.AddField(
            model_name='withdrawalwindow',
            name='fee_type',
            field=models.CharField(choices=[('percent', 'Percentage of withdrawal'), ('flat', 'Flat amount')], default='percent', help_text='Charge the fee as a percentage of the withdrawal, or a flat amount', max_length=10),
        ),
        migrations.AlterField(
            model_name='withdrawalwindow',
            name='fee_percent',
            field=models.DecimalField(decimal_places=2, default=5, help_text="Used when fee type is 'Percentage' — e.g. 5 for 5%", max_digits=6),
        ),
    ]
