# Generated by Django 5.2.15 on 2026-06-28 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_withdrawalwindow_fee_flat_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Ryder Assistant', max_length=100)),
                ('provider', models.CharField(default='deepseek', max_length=50)),
                ('api_key', models.CharField(blank=True, help_text='DeepSeek API key (the client buys this)', max_length=255)),
                ('base_url', models.CharField(default='https://api.deepseek.com', help_text='OpenAI-compatible base URL', max_length=255)),
                ('model_name', models.CharField(default='deepseek-chat', help_text='e.g. deepseek-chat', max_length=100)),
                ('extra_instructions', models.TextField(blank=True, help_text='Optional extra persona/policy instructions appended to the system prompt')),
                ('is_enabled', models.BooleanField(default=True)),
                ('human_handoff_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AI Assistant Config',
                'verbose_name_plural': 'AI Assistant Config',
            },
        ),
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, help_text='Anonymous session identifier', max_length=120)),
                ('status', models.CharField(choices=[('ai_active', 'AI Active'), ('human_requested', 'Human Requested'), ('human_active', 'Human Active'), ('closed', 'Closed')], default='ai_active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_chats', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('agent', 'Human Agent'), ('system', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.chatconversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
