# Generated by Django 5.2.15 on 2026-07-02 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_chatconfig_chatconversation_chatmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto_currency', models.CharField(choices=[('BTC', 'Bitcoin (BTC)'), ('ETH', 'Ethereum (ETH)'), ('USDT', 'Tether (USDT TRC20)')], max_length=10)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('crypto_amount', models.DecimalField(decimal_places=8, max_digits=18)),
                ('tx_hash', models.CharField(help_text='Blockchain Transaction ID', max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified & Credited'), ('failed', 'Verification Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_deposits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
