# Generated by Django 5.2.15 on 2026-07-02 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='country_code',
            field=models.CharField(blank=True, help_text='ISO 3166-1 alpha-2 country code', max_length=10, null=True),
        ),
    ]
