# Generated by Django 5.2.15 on 2026-07-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_userprofile_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='browser',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='connection_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_active_online',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='network',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='investmentasset',
            name='daily_return_percent',
            field=models.DecimalField(decimal_places=3, default=0.021, help_text='Daily earnings as a percent of the invested amount, e.g. 0.021 for ~8% APY', max_digits=6),
        ),
    ]
