# Generated by Django 5.2.15 on 2026-07-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_admindevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptodeposit',
            name='status',
            field=models.CharField(choices=[('awaiting_payment', 'Awaiting Payment'), ('pending', 'Pending Verification'), ('verified', 'Verified & Credited'), ('failed', 'Verification Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='cryptodeposit',
            name='tx_hash',
            field=models.CharField(blank=True, help_text='Blockchain Transaction ID', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='investmentasset',
            name='asset_type',
            field=models.CharField(choices=[('truck', 'Truck'), ('van', 'Van'), ('bike', 'Bike'), ('car', 'Car'), ('tractor', 'Tractor'), ('bus', 'Bus')], default='truck', max_length=10),
        ),
    ]
