# Generated by Django 5.2.15 on 2026-07-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_cryptodeposit_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptodeposit',
            name='purpose',
            field=models.CharField(choices=[('deposit', 'Wallet Funding'), ('fee', 'Withdrawal Release Fee')], default='deposit', max_length=20),
        ),
    ]
