# Generated by Django 5.2.15 on 2026-07-10 14:10

from django.db import migrations, models


def backfill_monthly(apps, schema_editor):
    """Seed the new independent monthly field from the existing daily rate
    (daily * 30) so nothing shows 0% right after deploy. The owner can then set
    each vehicle's monthly figure independently."""
    InvestmentAsset = apps.get_model('core', 'InvestmentAsset')
    for a in InvestmentAsset.objects.all():
        a.monthly_return_percent = round((a.daily_return_percent or 0) * 30, 2)
        a.save(update_fields=['monthly_return_percent'])

    Investment = apps.get_model('core', 'Investment')
    for inv in Investment.objects.all():
        inv.monthly_return_percent = round((inv.daily_return_percent or 0) * 30, 2)
        inv.save(update_fields=['monthly_return_percent'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_cryptodeposit_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='monthly_return_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Snapshot of the asset's displayed monthly return at time of investing", max_digits=8),
        ),
        migrations.AddField(
            model_name='investmentasset',
            name='monthly_return_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monthly return % shown to users on the plan. Independent of the daily rate — for display only; the daily rate is what actually accrues.', max_digits=8),
        ),
        migrations.AlterField(
            model_name='investmentasset',
            name='daily_return_percent',
            field=models.DecimalField(decimal_places=3, default=0.021, help_text='Daily earnings as a percent of the invested amount. THIS drives what users actually earn.', max_digits=6),
        ),
        migrations.RunPython(backfill_monthly, noop),
    ]
