# Generated by Django 5.2.15 on 2026-07-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_investment_monthly_return_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatconversation',
            name='agent_typing_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='user_typing_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
