# Generated by Django 5.2.15 on 2026-08-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_chatconversation_agent_typing_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatconversation',
            name='guest_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='guest_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='guest_country_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='guest_ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
