# Generated by Django 5.2.15 on 2026-08-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_chatconversation_guest_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='seo_description',
            field=models.CharField(blank=True, help_text='Custom meta description for Google (max 155 chars recommended). Leave blank to auto-generate.', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords for this page. Leave blank to use defaults.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Custom title for Google (max 60 chars recommended). Leave blank to auto-generate.', max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='investmentasset',
            name='seo_description',
            field=models.CharField(blank=True, help_text='Custom meta description for Google (max 155 chars recommended). Leave blank to auto-generate.', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='investmentasset',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords for this page. Leave blank to use defaults.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investmentasset',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Custom title for Google (max 60 chars recommended). Leave blank to auto-generate.', max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='seo_description',
            field=models.CharField(blank=True, help_text='Custom meta description for Google (max 155 chars recommended). Leave blank to auto-generate.', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords for this page. Leave blank to use defaults.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Custom title for Google (max 60 chars recommended). Leave blank to auto-generate.', max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='seo_description',
            field=models.CharField(blank=True, help_text='Custom meta description for Google (max 155 chars recommended). Leave blank to auto-generate.', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords for this page. Leave blank to use defaults.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Custom title for Google (max 60 chars recommended). Leave blank to auto-generate.', max_length=70, null=True),
        ),
    ]
