name: Keep Alive Ping

on:
  schedule:
    - cron: '*/10 * * * *' # Runs every 10 minutes
  workflow_dispatch: # Allows manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Health Check URL
        run: |
          curl -s -o /dev/null -w "%{http_code}" https://www.ryder-pro.com/health/
